# Generated by Django 4.2.11 on 2024-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names_man', models.CharField(blank=True, max_length=255, null=True, verbose_name="Man's name")),
                ('names_woman', models.CharField(blank=True, max_length=255, null=True, verbose_name="Woman's name")),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
    ]
